### ISSUE TITLE
[Question] Get the black and compact icon style

### ISSUE THREAD

**Issue by jlstanus** [Dominique92/ol-geocoder#156]
I would like to have the same style as here https://jsfiddle.net/jonataswalker/c4qv9afb/
where the icone is compact and why not the style is black.
I have liiked in the https://unpkg.com/ol-geocoder@3.0.1/dist/ol-geocoder.min.css but nothing .

Can you help me?

Tks

**Comment by jonataswalker** [comment]
Sorry @jlstanus but I don't think I understand what you need. Do you mean this?

```css
.ol-control button { 
    background-color: rgba(40, 40, 40, 0.8) !important;
}
.ol-control button:hover { 
    background-color: rgba(40, 40, 40, 1) !important;
}
```
